apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: flask-k-s
build:
  artifacts:
  - image: test-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - hello-deployment.yaml
    - hello-service.yaml
    - test-ingress.yaml
    - test/test-ingress.yaml
