apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: flask-k-s
build:
  artifacts:
  - image: hello-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: dev
    manifests:
    - k8s/dev-namespace.yaml
    - k8s/dev-ingress.yaml
    - k8s/hello-deployment.yaml
    - k8s/hello-service.yaml
